GET http://localhost:3000/api/database/display-backups-files

###
DELETE http://localhost:3000/api/database/delete/backup_postgres_2024-11-24T19-34-57-856Z.sql

### restore-file-backup
POST http://localhost:3000/api/database/restore-file-backup/backup-mysql-241124-231936.sql


### Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Frank",
  "email": "frank123456@example.com",
  "password": "password123"
}

### Obtener todos los usuarios
GET http://localhost:3000/api/users

### dropDatabase
DELETE http://localhost:3000/api/info/dropDatabase
Authorization: true