### Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Frank",
  "email": "frank@example.com",
  "password": "password123"
}

### Obtener todos los usuarios
GET http://localhost:3000/api/users

### Obtener un usuario por ID
GET http://localhost:3000/api/users/1

### Actualizar un usuario por ID
PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
  "firstName": "John222",
  "email": "john.doe222@example.com",
  "password": "password123222"
}

### Eliminar un usuario por ID
DELETE http://localhost:3000/api/users/1
